package com.porest.desk.expense.domain;

import com.porest.desk.expense.type.ExpenseType;
import com.porest.desk.user.domain.User;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.test.util.ReflectionTestUtils;

import java.time.LocalDateTime;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * 카드 이월 거래는 <b>가계부 집계에서만</b> 빠진다(D4 후속 결정, 2026-09-18).
 *
 * <p>카드를 만들 때 적은 "이전 미결제 사용액" 은 앱을 쓰기 전에 이미 쓴 돈이다. 그걸 지출
 * 합계에 세면 카드를 등록한 달만 몇십만 원이 솟는다 — 사용자가 그 달에 쓴 돈이 아니다.
 *
 * <p>반대로 카드 쪽에서는 빼면 안 된다. 그 거래가 곧 카드의 미결제 잔액이고 첫 회차 청구다.
 * 빼는 순간 D4("잔액 = 거래 합")가 풀려 한도 사용과 청구가 다시 갈린다.
 *
 * <p>그래서 규칙이 둘이다 — {@code countable}(카드) 과 {@code ledgerCountable}(가계부).
 * 같은 목록을 넣고 둘을 나란히 본다.
 */
@DisplayName("카드 이월 거래는 가계부 합계에서만 빠진다")
class CardCarryoverAggregateTest {

    private static final LocalDateTime NOW = LocalDateTime.of(2026, 9, 18, 12, 0);

    private User user() {
        User u = User.createUser(null, "tester", "테스터", "tester@porest.com");
        ReflectionTestUtils.setField(u, "rowId", 1L);
        return u;
    }

    private Expense expense(long rowId, long amount, String autoSource) {
        Expense e = Expense.createExpense(
            user(), null, null, ExpenseType.EXPENSE, amount, "설명",
            LocalDateTime.of(2026, 9, 10, 12, 0), "가맹점", "CARD", null, null, null, null);
        ReflectionTestUtils.setField(e, "rowId", rowId);
        if (autoSource != null) {
            e.markAutoGenerated(autoSource);
        }
        return e;
    }

    @Test
    @DisplayName("가계부 합계에는 이월 30만이 없다 — 등록한 달의 지출이 아니다")
    void ledgerExcludesCarryover() {
        List<Expense> all = List.of(
            expense(1L, 12_000L, null),
            expense(2L, 300_000L, Expense.AUTO_SOURCE_CARD_CARRYOVER));

        List<Expense> ledger = ExpenseAggregates.ledgerCountable(all, NOW);

        assertThat(ledger).extracting(Expense::getRowId).containsExactly(1L);
        assertThat(ExpenseAggregates.expenseSum(ledger)).isEqualTo(12_000L);
    }

    @Test
    @DisplayName("카드 쪽 합계에는 그대로 있다 — 빼면 잔액 = 거래 합이 풀린다")
    void cardKeepsCarryover() {
        List<Expense> all = List.of(
            expense(1L, 12_000L, null),
            expense(2L, 300_000L, Expense.AUTO_SOURCE_CARD_CARRYOVER));

        List<Expense> card = ExpenseAggregates.countable(all, NOW);

        assertThat(card).extracting(Expense::getRowId).containsExactly(1L, 2L);
        assertThat(ExpenseAggregates.expenseSum(card)).isEqualTo(312_000L);
    }

    @Test
    @DisplayName("다른 시스템 거래(매도 실현손익·이체 이자)는 가계부에 그대로 남는다")
    void otherAutoSourcesStay() {
        List<Expense> all = List.of(expense(3L, 5_000L, "TRADE_REALIZED"));

        assertThat(ExpenseAggregates.ledgerCountable(all, NOW))
            .as("이월만 빼는 규칙이다 — 자동 생성 전부를 빼면 실현손익·이자가 사라진다")
            .hasSize(1);
    }

    @Test
    @DisplayName("환불·예정 규칙은 그대로 겹쳐 적용된다")
    void stacksWithRefundAndFuture() {
        Expense refunded = expense(4L, 9_000L, null);
        refunded.markRefunded(NOW);
        Expense future = Expense.createExpense(
            user(), null, null, ExpenseType.EXPENSE, 7_000L, "예정",
            NOW.plusDays(3), "가맹점", "CARD", null, null, null, null);

        List<Expense> ledger = ExpenseAggregates.ledgerCountable(
            List.of(expense(1L, 12_000L, null), refunded, future), NOW);

        assertThat(ledger).extracting(Expense::getRowId).containsExactly(1L);
    }
}
