package com.porest.desk.expense.service;

import com.porest.core.exception.EntityNotFoundException;
import com.porest.core.exception.ForbiddenException;
import com.porest.core.exception.InvalidValueException;
import com.porest.desk.common.exception.DeskErrorCode;
import com.porest.desk.expense.domain.Expense;
import com.porest.desk.expense.domain.ExpenseCategory;
import com.porest.desk.expense.domain.ExpenseSplit;
import com.porest.desk.expense.repository.ExpenseCategoryRepository;
import com.porest.desk.expense.repository.ExpenseRepository;
import com.porest.desk.expense.repository.ExpenseSplitRepository;
import com.porest.desk.expense.service.dto.ExpenseSplitServiceDto;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Collections;
import java.util.IdentityHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
@Slf4j
@Transactional(readOnly = true)
public class ExpenseSplitServiceImpl implements ExpenseSplitService {
    private final ExpenseSplitRepository expenseSplitRepository;
    private final ExpenseRepository expenseRepository;
    private final ExpenseCategoryRepository expenseCategoryRepository;

    @Override
    public List<ExpenseSplitServiceDto.SplitInfo> getSplits(Long expenseRowId, Long userRowId) {
        Expense expense = findExpenseOrThrow(expenseRowId);
        validateExpenseOwnership(expense, userRowId);

        return expenseSplitRepository.findByExpense(expenseRowId).stream()
            .map(ExpenseSplitServiceDto.SplitInfo::from)
            .toList();
    }

    @Override
    @Transactional
    public List<ExpenseSplitServiceDto.SplitInfo> replaceSplits(ExpenseSplitServiceDto.ReplaceCommand command) {
        log.debug("분할 항목 교체 시작: expenseRowId={}", command.expenseRowId());

        Expense expense = findExpenseOrThrow(command.expenseRowId());
        validateExpenseOwnership(expense, command.userRowId());

        // 금액이 잠긴 거래에는 분할을 둘 수 없다. 분할 합은 거래 금액과 맞아야 하는데,
        // 실현손익은 재계산으로 금액이 바뀐다 — 그때 분할만 옛 금액으로 남아 합이 어긋난다.
        if (expense.isAutoGenerated()) {
            throw new InvalidValueException(DeskErrorCode.EXPENSE_AUTO_GENERATED_READONLY);
        }

        List<ExpenseSplitServiceDto.SplitCommand> incoming = command.splits() != null ? command.splits() : List.of();
        validateAmountSum(expense, incoming);

        // rowId 로 맞춘다 — 있으면 제자리 수정, 없으면 신규, 안 온 건 삭제.
        // 통째로 지우고 새로 만들면 수정할 때마다 죽은 행이 쌓이고 감사 컬럼이 리셋된다.
        List<ExpenseSplit> existing = expenseSplitRepository.findByExpense(command.expenseRowId());
        Map<Long, ExpenseSplit> byId = existing.stream()
            .filter(sp -> sp.getRowId() != null)
            .collect(Collectors.toMap(ExpenseSplit::getRowId, sp -> sp, (a, b) -> a));
        Set<ExpenseSplit> kept = Collections.newSetFromMap(new IdentityHashMap<>());

        for (int i = 0; i < incoming.size(); i++) {
            ExpenseSplitServiceDto.SplitCommand sc = incoming.get(i);
            ExpenseCategory category = expenseCategoryRepository.findById(sc.categoryRowId())
                .orElseThrow(() -> new EntityNotFoundException(DeskErrorCode.EXPENSE_CATEGORY_NOT_FOUND));
            validateCategoryOwnership(category, command.userRowId()); // 남의 카테고리를 분할에 지정 차단
            // 거래 유형 == 분할 카테고리 유형 강제 (수입 거래엔 수입 카테고리만).
            // 분할은 부모 거래 유형으로 집계되므로 유형이 다르면 카테고리 통계가 오염된다(거래/템플릿과 대칭, #2 확장).
            if (category.getExpenseType() != expense.getExpenseType()) {
                throw new InvalidValueException(DeskErrorCode.EXPENSE_TYPE_CATEGORY_MISMATCH);
            }
            // 정책: 상위(자식 보유) 카테고리에는 거래(분할)를 둘 수 없음.
            if (expenseCategoryRepository.hasChildren(category.getRowId())) {
                throw new InvalidValueException(DeskErrorCode.EXPENSE_CATEGORY_NOT_LEAF);
            }
            int order = sc.sortOrder() != null ? sc.sortOrder() : i;
            // 남의 분할 rowId 를 보내도 이 거래의 것만 맵에 있어 못 가져간다 — 못 찾으면 신규다.
            ExpenseSplit found = sc.rowId() != null ? byId.get(sc.rowId()) : null;
            if (found != null) {
                found.update(category, sc.amount(), sc.label(), order);
                kept.add(found);
            } else {
                expenseSplitRepository.save(
                    ExpenseSplit.create(expense, category, sc.amount(), sc.label(), order));
            }
        }
        // 목록에서 빠진 것만 지운다. rowId 로 매칭되지 않은 것도 여기 걸린다.
        for (ExpenseSplit sp : existing) {
            if (!kept.contains(sp)) {
                sp.deleteSplit();
            }
        }

        log.info("분할 항목 교체 완료: expenseRowId={}, count={}", command.expenseRowId(), incoming.size());

        return expenseSplitRepository.findByExpense(command.expenseRowId()).stream()
            .map(ExpenseSplitServiceDto.SplitInfo::from)
            .toList();
    }

    @Override
    @Transactional
    public void deleteAllSplits(Long expenseRowId, Long userRowId) {
        Expense expense = findExpenseOrThrow(expenseRowId);
        validateExpenseOwnership(expense, userRowId);

        expenseSplitRepository.deleteByExpense(expenseRowId);
        log.info("분할 항목 전체 삭제 완료: expenseRowId={}", expenseRowId);
    }

    private void validateAmountSum(Expense expense, List<ExpenseSplitServiceDto.SplitCommand> splits) {
        if (splits.isEmpty()) return;
        // 개별 금액부터 본다. 합계만 검사하면 [+30,000, -20,000] 처럼 서로 상쇄되는 조합이
        // 통과해 카테고리 통계에 음수 항목이 박힌다(컬럼 정의도 '절대값'이다).
        for (ExpenseSplitServiceDto.SplitCommand sc : splits) {
            if (sc.amount() == null || sc.amount() <= 0) {
                throw new InvalidValueException(DeskErrorCode.EXPENSE_INVALID_AMOUNT);
            }
        }
        long sum = splits.stream().mapToLong(ExpenseSplitServiceDto.SplitCommand::amount).sum();
        long expected = Math.abs(expense.getAmount());
        if (sum != expected) {
            log.warn("분할 합계 불일치 - expenseRowId={}, expected={}, actual={}",
                expense.getRowId(), expected, sum);
            throw new InvalidValueException(DeskErrorCode.EXPENSE_SPLIT_AMOUNT_MISMATCH);
        }
    }

    private void validateCategoryOwnership(ExpenseCategory category, Long userRowId) {
        if (!category.getUser().getRowId().equals(userRowId)) {
            log.warn("지출 카테고리 소유권 검증 실패 - categoryId={}, ownerRowId={}, requestUserRowId={}",
                category.getRowId(), category.getUser().getRowId(), userRowId);
            throw new ForbiddenException(DeskErrorCode.EXPENSE_ACCESS_DENIED);
        }
    }

    private Expense findExpenseOrThrow(Long expenseRowId) {
        return expenseRepository.findById(expenseRowId)
            .orElseThrow(() -> new EntityNotFoundException(DeskErrorCode.EXPENSE_NOT_FOUND));
    }

    private void validateExpenseOwnership(Expense expense, Long userRowId) {
        if (!expense.getUser().getRowId().equals(userRowId)) {
            log.warn("거래 소유권 검증 실패 - expenseRowId={}, ownerRowId={}, requestUserRowId={}",
                expense.getRowId(), expense.getUser().getRowId(), userRowId);
            throw new ForbiddenException(DeskErrorCode.EXPENSE_ACCESS_DENIED);
        }
    }
}
